

import { Translations, AdBanner, Service, Product, BlogPost, GalleryItem } from './types';

export const INSTAGRAM_LINK = "https://instagram.com/shenayileri";
export const PHONE_NUMBER = "017663195289";

export const HERO_IMAGE = "https://images.unsplash.com/photo-1596436570226-f78a87383637?q=80&w=2074&auto=format&fit=crop"; 
// Changed to placeholder as requested
export const ABOUT_IMAGE = "https://placehold.co/600x800/png?text=Kein+Foto";

export const DEFAULT_ABOUT_TEXT = "Shenay Ileri kombiniert jahrelange Erfahrung in der Schönheits- und Ästhetikbranche mit dem Ziel, das einzigartige Strahlen jeder Frau zum Vorschein zu bringen. Als Absolventin der Fames Face Akademie ist Shenay nicht nur Visagistin, sondern auch Schönheitscoach.";

export const TRANSLATIONS: Translations = {
  en: {
    nav: {
      home: "Home",
      services: "Services",
      products: "Shop",
      booking: "Book Now",
      blog: "Blog",
      about: "About",
      app: "AI Beauty",
      gallery: "Gallery",
      contact: "Contact",
      admin: "Admin"
    },
    hero: {
      title: "Reveal Your True Beauty",
      subtitle: "Professional artistry meets Artificial Intelligence. Discover the perfect makeup for your unique face shape with Shenay Ileri.",
      cta: "Book Appointment",
      aiBtn: "Try AI Analysis",
      instagramBtn: "Follow on Instagram",
      instagram: "Follow on Instagram"
    },
    contact: {
        title: "Contact & Booking",
        phone: "Phone",
        email: "Email",
        address: "Address",
        whatsapp: "WhatsApp",
        followUs: "Follow Us"
    },
    payment: {
      title: "Bank Transfer Payment",
      description: "To unlock the full premium analysis and product guide, please proceed via bank transfer.",
      payButton: "Proceed to Transfer",
      secure: "Secure Bank Transfer",
      cardHolder: "ACCOUNT HOLDER",
      expires: "VALID THRU",
      bankTransferTitle: "Bank Transfer Details",
      bankTransferDesc: "Please transfer the amount to the account below to unlock your report.",
      sentButton: "I Have Sent the Payment"
    },
    admin: {
      title: "Shenay Admin Dashboard",
      adsTitle: "Manage Campaign Ads",
      uploadAd: "Upload New Banner",
      loginTitle: "Admin Login",
      username: "Username",
      password: "Password",
      loginBtn: "Login",
      forgotPassword: "Forgot Password?",
      recoveryTitle: "Account Recovery",
      recoveryDesc: "For security reasons, please contact the system developer to reset your credentials.",
      lockedMessage: "Too many failed attempts. Login locked for security.",
      loginError: "Invalid email or password.",
      emailSupport: "Email Support",
      tryAgainIn: "Try again in",
      emailLabel: "Email",
      tabs: {
        overview: "Overview",
        appointments: "Appointments",
        services: "Services",
        products: "Products",
        blog: "Blog",
        gallery: "Gallery",
        testimonials: "Testimonials",
        team: "Team",
        banners: "Banners",
        invoices: "Invoices",
        orders: "Orders",
        settings: "General Settings"
      },
      orderStatus: {
        pending: "Pending",
        shipped: "Shipped",
        completed: "Completed",
        cancelled: "Cancelled",
        return_requested: "Return Requested",
        returned: "Returned",
        refunded: "Refunded"
      },
      modalTitle: "Edit / Add",
      cancel: "Cancel",
      saveAndPublish: "Save & Publish",
      deleteConfirm: "Are you sure you want to delete this item?",
      saveSuccess: "Settings saved successfully!",
      saveError: "Error saving settings",
      deleteError: "Error deleting item",
      invoiceTitle: "Invoice Generator",
      invoiceNo: "Invoice No",
      date: "Date",
      customerName: "Customer Name",
      address: "Address",
      items: "Items",
      addPhoto: "Add Photo",
      addVideo: "Add Video",
      remove: "Remove",
      mediaGallery: "Media Gallery",
      addItem: "+ Add Item",
      printDownload: "Print / Download PDF",
      legalInfo: "Legal Company Info",
      companyName: "Company Name",
      companyAddress: "Company Address",
      taxId: "Tax ID",
      vatId: "VAT ID",
      jurisdiction: "Jurisdiction",
      bankInfo: "Bank Information",
      bankName: "Bank Name",
      iban: "IBAN",
      bic: "BIC/SWIFT",
      accountHolder: "Account Holder",
      saveLegalInfo: "Save Company Info",
      siteSettings: "General Site Settings",
      siteTitle: "Site Title",
      heroSlogan: "Hero Slogan",
      heroBackground: "Hero Background",
      change: "Change",
      heroDesc: "The large background image at the top of the home page. Recommended size: 1920x1080px (Horizontal)",
      contactInfo: "Contact Information",
      phone: "Phone",
      email: "Email",
      aboutMe: "About Me",
      saveAll: "SAVE ALL SETTINGS & PUBLISH",
      logout: "Logout",
      newAdd: "Add New",
      management: "Management",
      noOrders: "No orders yet.",
      appointmentRequests: "Appointment Requests",
      customer: "Customer",
      service: "Service",
      status: "Status",
      action: "Action",
      confirmed: "Confirmed",
      waiting: "Waiting",
      cancelled: "Cancelled",
      amount: "Amount",
      id: "ID",
      saving: "Saving...",
      generalSiteSettings: "General Site Settings",
      homeBackground: "Home Background",
      heroImage: "Hero Image",
      recommendedSize: "Recommended size",
      changePhoto: "Change Photo",
      saveAllSettings: "SAVE ALL SETTINGS",
      galleryManagement: "Gallery Management",
      addNewPhoto: "Add New Photo",
      incomingOrders: "Incoming Orders",
      noOrdersYet: "No orders yet.",
      stock: "Stock",
      category: "Category",
      rating: "Rating",
      comment: "Comment",
      role: "Role",
      bio: "Bio",
      instagramLink: "Instagram Link",
      link: "Link",
      excerpt: "Excerpt",
      price: "Price",
      titleLabel: "Title",
      invoiceHeader: "INVOICE",
      invoiceRecipient: "Recipient",
      invoiceDesc: "Description",
      invoicePriceNet: "Price (Net)",
      invoiceVat: "VAT",
      invoiceTotal: "Total",
      invoiceSumNet: "Sum Net",
      invoicePlusVat: "plus VAT 19%",
      invoiceTotalAmount: "Total Amount",
      invoiceBank: "Bank Details",
      invoiceThanks: "Thank you for your order!",
      invoiceDate: "Date",
      invoiceNoLabel: "Invoice No",
      pricePlaceholder: "e.g. €25.00",
      ratingPlaceholder: "(1-5)",
      currencySymbol: "€",
      vatSymbol: "%"
    },
    sections: {
      servicesTitle: "Exclusive Services",
      productsTitle: "Signature Products",
      blogTitle: "Beauty Trends & Tips",
      bookTitle: "Book an Appointment",
      aboutTitle: "About Shenay Ileri",
      aboutText: "With years of experience in the beauty and aesthetics world, Shenay Ileri aims to reveal the unique sparkle within every woman. A graduate of Fames Face Academy, Shenay is not just a makeup artist but also a beauty coach.",
      aboutRoles: [
          "Founder of Bridal Room & Academy",
          "Professional Makeup & Hair Design",
          "Medical Skin Care Expert (Aquafacial)"
      ],
      bookBtn: "Confirm Booking",
      buyBtn: "Add to Cart",
      readMore: "Read More",
      returnBtn: "Create Return Request",
      bookFormName: "Full Name",
      bookFormNamePlaceholder: "Enter Full Name",
      bookFormPhone: "Phone Number",
      bookFormPhonePlaceholder: "+90 ...",
      bookFormDate: "Date",
      bookFormTime: "Time",
      bookFormService: "Service",
      bookFormSuccess: "Reservation request received!",
      bookServiceOptions: {
        bridal: "Bridal Makeup",
        special: "Special Event Makeup",
        skincare: "Skin Care",
        brows: "Brow Design"
      },
      galleryTitle: "Portfolio & Gallery",
      gallerySubtitle: "Witness the most natural and impressive forms of beauty. Here are selections from our work.",
      contactTitle: "Get in Touch",
      testimonialsTitle: "Client Testimonials",
      teamTitle: "Meet Our Team",
      professionalArtist: "Professional Artist",
      serviceDetailsTitle: "Service Details",
      bookNow: "Book Now",
      bookDescription: "Reserve your spot for this service now. Reveal your beauty with professional touches.",
      onlineBooking: "7/24 Online Booking",
      supportContact: "Contact us for support",
      outOfStock: "OUT OF STOCK",
      soldOut: "SOLD OUT",
      notesLabel: "Notes (Optional)",
      notesPlaceholder: "Anything you'd like to add...",
      goBack: "Go Back",
      share: "Share",
      whatsappTitle: "Fast Contact with WhatsApp",
      whatsappDesc: "You can write to us via WhatsApp to book an appointment or ask for information.",
      followUs: "Follow Us",
      all: "All",
      other: "Other",
      galleryAlt: "Gallery Image"
    },
    cart: {
      title: "My Shopping Bag",
      empty: "Your bag is empty.",
      total: "Total",
      checkout: "Confirm Order",
      shippingTitle: "Shipping Details",
      shippingDesc: "Please provide your details to proceed.",
      formName: "Full Name",
      formPhone: "Phone Number",
      formEmail: "Email Address",
      formAddress: "Address",
      formCity: "City",
      formZip: "Zip Code",
      back: "Back",
      proceed: "Proceed to Payment",
      orderSuccessTitle: "Order Received!",
      orderSuccessMsg: "Thank you! Your order has been successfully recorded in our system.",
      continueShop: "Continue Shopping"
    },
    returns: {
      title: "Returns & Refunds",
      policyTitle: "Return Policy",
      formTitle: "Return Request Form",
      orderId: "Order Number",
      email: "Email Address",
      reason: "Reason for Return",
      submitBtn: "Submit Request",
      placeholderId: "e.g. 1001",
      placeholderEmail: "Email used for order",
      placeholderReason: "Please briefly describe why you are returning the item..."
    },
    app: {
      title: "AI Makeup Consultant",
      subtitle: "Upload your photo for a personalized professional makeup analysis.",
      upload: "Upload Photo",
      analyzing: "Analyzing...",
      freeSummary: "Free Face Profile",
      summaryTitle: "Your Face Profile",
      faceShape: "Face Shape",
      skinTone: "Skin Tone",
      premiumRequired: "Premium Content (Locked)",
      unlockPremium: "Unlock via Bank Transfer",
      premiumPrice: "€5.00",
      suggestions: "Detailed Application Guide",
      paletteTitle: "Your Color Palette",
      stepsTitle: "Step-by-Step Guide",
      productsTitle: "Recommended Products",
      dayNightTitle: "Day & Night Look",
      proFixes: "Pro Fixes",
      time: "Duration",
      minutes: "Min",
      day: "DAY",
      night: "NIGHT",
      technique: "Technique",
      symmetry: "Symmetry",
      eyeShape: "Eye Shape",
      option: "Option",
      emptyProducts: "No specific products required for this look.",
      defaultFixes: "Your facial features are quite balanced. You can highlight your natural beauty with minimal touches.",
      errorProcessing: "Error processing image.",
      errorAnalysis: "Analysis error.",
      premiumAccess: "Premium Access",
      freePreview: "Free Preview",
      changePhoto: "Change Photo",
      analyze: "Analyze",
      aiRequirement: "Advanced AI Analysis requires a clear, well-lit photo.",
      virtualConsultant: "Your Virtual Beauty Consultant",
      aiDesc: "Discover your face shape, skin tone, and the colors that suit you best with our AI-powered analysis tool. Upload your photo and get professional recommendations instantly.",
      startFreeAnalysis: "Start Free Analysis",
      personalReport: "Personal Report",
      matchSuccess: "98% Match Success"
    }
  },
  tr: {
    nav: {
      home: "Ana Sayfa",
      services: "Hizmetler",
      products: "Ürünler",
      booking: "Randevu",
      blog: "Blog",
      about: "Hakkımda",
      app: "AI Analiz",
      gallery: "Galeri",
      contact: "İletişim",
      admin: "Yönetim"
    },
    hero: {
      title: "Gerçek Güzelliğinizi Ortaya Çıkarın",
      subtitle: "Profesyonel sanat Yapay Zeka ile buluşuyor. Shenay İleri ile yüz şeklinize en uygun makyajı keşfedin.",
      cta: "Randevu Al",
      aiBtn: "AI Analizini Dene",
      instagramBtn: "Instagram'da Takip Et",
      instagram: "Instagram'da Takip Et"
    },
    contact: {
        title: "İletişim & Randevu",
        phone: "Tel",
        email: "E-posta",
        address: "Adres",
        whatsapp: "WhatsApp",
        followUs: "Bizi Takip Edin"
    },
    payment: {
      title: "Ödeme Yöntemi: Banka Havalesi",
      description: "Premium analize ve detaylı rapora erişmek için lütfen ödemeyi banka havalesi ile yapınız.",
      payButton: "Havaleye Geç",
      secure: "Güvenli Banka Havalesi",
      cardHolder: "HESAP SAHİBİ",
      expires: "GEÇERLİLİK",
      bankTransferTitle: "Banka Hesap Bilgileri",
      bankTransferDesc: "Raporun kilidini açmak için lütfen tutarı aşağıdaki hesaba gönderiniz.",
      sentButton: "Ödemeyi Gönderdim"
    },
    admin: {
      title: "Shenay Yönetim Paneli",
      adsTitle: "Kampanya Reklamlarını Yönet",
      uploadAd: "Yeni Banner Yükle",
      loginTitle: "Yönetici Girişi",
      username: "Kullanıcı Adı",
      password: "Şifre",
      loginBtn: "Giriş Yap",
      forgotPassword: "Şifremi Unuttum",
      recoveryTitle: "Hesap Kurtarma",
      recoveryDesc: "Güvenlik nedeniyle şifre sıfırlama işlemi için lütfen sistem geliştiricisi ile iletişime geçiniz.",
      lockedMessage: "Çok fazla başarısız deneme. Güvenlik için giriş kilitlendi.",
      loginError: "Hatalı email veya şifre.",
      emailSupport: "E-posta Desteği",
      tryAgainIn: "Tekrar dene",
      emailLabel: "E-posta",
      tabs: {
        overview: "Genel Bakış",
        appointments: "Randevular",
        services: "Hizmetler",
        products: "Ürünler",
        blog: "Blog",
        gallery: "Galeri",
        testimonials: "Yorumlar",
        team: "Ekip",
        banners: "Banner",
        invoices: "Faturalar",
        orders: "Siparişler",
        settings: "Genel Ayarlar"
      },
      orderStatus: {
        pending: "Beklemede",
        shipped: "Kargolandı",
        completed: "Tamamlandı",
        cancelled: "İptal Edildi",
        return_requested: "İade Talebi",
        returned: "İade Edildi",
        refunded: "Geri Ödendi"
      },
      modalTitle: "Düzenle / Ekle",
      cancel: "İptal",
      saveAndPublish: "Kaydet & Yayınla",
      deleteConfirm: "Silmek istediğinize emin misiniz?",
      saveSuccess: "Ayarlar başarıyla kaydedildi!",
      saveError: "Ayarlar kaydedilemedi",
      deleteError: "Silme hatası",
      invoiceTitle: "Fatura Oluşturucu",
      invoiceNo: "Fatura No",
      date: "Tarih",
      customerName: "Müşteri Adı",
      address: "Adres",
      items: "Kalemler",
      addPhoto: "Fotoğraf Ekle",
      addVideo: "Video Ekle",
      remove: "Kaldır",
      mediaGallery: "Medya Galerisi",
      addItem: "+ Kalem Ekle",
      printDownload: "Yazdır / PDF İndir",
      legalInfo: "Yasal Firma Bilgileri",
      companyName: "Firma Adı",
      companyAddress: "Firma Adresi",
      taxId: "Vergi No",
      vatId: "KDV No",
      jurisdiction: "Mahkeme Yeri",
      bankInfo: "Banka Bilgileri",
      bankName: "Banka Adı",
      iban: "IBAN",
      bic: "BIC/SWIFT",
      accountHolder: "Hesap Sahibi",
      saveLegalInfo: "Firma Bilgilerini Kaydet",
      siteSettings: "Genel Site Ayarları",
      siteTitle: "Site Başlığı",
      heroSlogan: "Hero Slogan",
      heroBackground: "Ana Sayfa Arka Planı",
      change: "Değiştir",
      heroDesc: "Ana sayfanın üst kısmında yer alan büyük arka plan görseli. Önerilen boyut: 1920x1080px (Yatay)",
      contactInfo: "İletişim Bilgileri",
      phone: "Telefon",
      email: "E-posta",
      aboutMe: "Hakkımda",
      saveAll: "TÜM AYARLARI KAYDET VE YAYINLA",
      logout: "Çıkış Yap",
      newAdd: "Yeni Ekle",
      management: "Yönetimi",
      noOrders: "Henüz sipariş yok.",
      appointmentRequests: "Randevu Talepleri",
      customer: "Müşteri",
      service: "Hizmet",
      status: "Durum",
      action: "İşlem",
      confirmed: "Onaylandı",
      waiting: "Bekliyor",
      cancelled: "İptal Edildi",
      amount: "Tutar",
      id: "ID",
      saving: "Kaydediliyor...",
      generalSiteSettings: "Genel Ayarlar",
      homeBackground: "Ana Sayfa Arka Planı",
      heroImage: "Hero Görseli",
      recommendedSize: "Önerilen boyut",
      changePhoto: "Fotoğraf Değiştir",
      saveAllSettings: "TÜM AYARLARI KAYDET VE YAYINLA",
      galleryManagement: "Galeri Yönetimi",
      addNewPhoto: "Yeni Fotoğraf Ekle",
      incomingOrders: "Gelen Siparişler",
      noOrdersYet: "Henüz sipariş yok.",
      stock: "Stok",
      category: "Kategori",
      rating: "Puan",
      comment: "Yorum",
      role: "Rol",
      bio: "Biyografi",
      instagramLink: "Instagram Linki",
      link: "Link",
      excerpt: "Özet",
      price: "Fiyat",
      titleLabel: "Başlık",
      invoiceHeader: "FATURA",
      invoiceRecipient: "Alıcı",
      invoiceDesc: "Açıklama",
      invoicePriceNet: "Fiyat (Net)",
      invoiceVat: "KDV",
      invoiceTotal: "Toplam",
      invoiceSumNet: "Net Toplam",
      invoicePlusVat: "KDV %19 dahil",
      invoiceTotalAmount: "Toplam Tutar",
      invoiceBank: "Banka Bilgileri",
      invoiceThanks: "Siparişiniz için teşekkürler!",
      invoiceDate: "Tarih",
      invoiceNoLabel: "Fatura No",
      pricePlaceholder: "Örn: €25.00",
      ratingPlaceholder: "(1-5)",
      currencySymbol: "€",
      vatSymbol: "%"
    },
    sections: {
      servicesTitle: "Hizmetlerimiz",
      productsTitle: "Öne Çıkan Ürünler",
      blogTitle: "Güzellik İpuçları & Blog",
      bookTitle: "Randevu Oluştur",
      aboutTitle: "Shenay İleri Hakkında",
      aboutText: "Shenay İleri, güzellik ve estetik dünyasında yıllara dayanan tecrübesiyle, her kadının içindeki eşsiz ışıltıyı ortaya çıkarmayı hedefler. Fames Face Akademie mezunu olan Shenay, sadece bir makyaj sanatçısı değil, aynı zamanda bir güzellik koçudur.",
      aboutRoles: [
          "Bridal Room & Academy Kurucusu",
          "Profesyonel Makyaj & Saç Tasarımı",
          "Medikal Cilt Bakımı Uzmanı (Aquafacial)"
      ],
      bookBtn: "Randevuyu Onayla",
      buyBtn: "Sepete Ekle",
      readMore: "Devamını Oku",
      returnBtn: "İade Talebi Oluştur",
      bookFormName: "Ad Soyad",
      bookFormNamePlaceholder: "İsim Giriniz",
      bookFormPhone: "Telefon",
      bookFormPhonePlaceholder: "+90 ...",
      bookFormDate: "Tarih",
      bookFormTime: "Saat",
      bookFormService: "Hizmet",
      bookFormSuccess: "Rezervasyon talebiniz alındı!",
      bookServiceOptions: {
        bridal: "Gelin Makyajı",
        special: "Özel Gün Makyajı",
        skincare: "Cilt Bakımı",
        brows: "Kaş Tasarım"
      },
      galleryTitle: "Portföy & Galeri",
      gallerySubtitle: "Güzelliğin en doğal ve etkileyici hallerine tanıklık edin. İşte çalışmalarımızdan seçkiler.",
      contactTitle: "Bize Ulaşın",
      testimonialsTitle: "Müşterilerimiz Ne Diyor?",
      teamTitle: "Ekibimizle Tanışın",
      professionalArtist: "Profesyonel Sanatçı",
      serviceDetailsTitle: "Hizmet Detayları",
      bookNow: "Randevu Al",
      bookDescription: "Bu hizmet için hemen yerinizi ayırtın. Profesyonel dokunuşlarla güzelliğinizi ortaya çıkarın.",
      onlineBooking: "7/24 Online Randevu",
      supportContact: "Destek için bize ulaşın",
      outOfStock: "STOKTA YOK",
      soldOut: "TÜKENDİ",
      notesLabel: "Notlar (Opsiyonel)",
      notesPlaceholder: "Eklemek istedikleriniz...",
      goBack: "Geri Dön",
      share: "Paylaş",
      whatsappTitle: "WhatsApp ile Hızlı İletişim",
      whatsappDesc: "Randevu almak veya bilgi sormak için WhatsApp üzerinden bize yazabilirsiniz.",
      followUs: "Bizi Takip Edin",
      all: "Hepsi",
      other: "Diğer",
      galleryAlt: "Galeri Görseli"
    },
    cart: {
      title: "Sepetim",
      empty: "Sepetiniz şu an boş.",
      total: "Toplam",
      checkout: "Siparişi Tamamla",
      shippingTitle: "Teslimat Bilgileri",
      shippingDesc: "Siparişinizin size ulaşması için lütfen bilgileri doldurun.",
      formName: "Ad Soyad",
      formPhone: "Telefon Numarası",
      formEmail: "E-posta Adresi",
      formAddress: "Açık Adres",
      formCity: "Şehir / İlçe",
      formZip: "Posta Kodu",
      back: "Geri",
      proceed: "Ödemeye Geç",
      orderSuccessTitle: "Siparişiniz Alındı!",
      orderSuccessMsg: "Teşekkürler! Siparişiniz başarıyla sistemimize kaydedildi.",
      continueShop: "Alışverişe Devam Et"
    },
    returns: {
      title: "İade & Geri Ödeme",
      policyTitle: "İade Koşulları",
      formTitle: "İade Talep Formu",
      orderId: "Sipariş Numarası",
      email: "E-Posta Adresi",
      reason: "İade Nedeni",
      submitBtn: "Talebi Gönder",
      placeholderId: "Örn: 1001",
      placeholderEmail: "Sipariş verirken kullandığınız email",
      placeholderReason: "Lütfen iade nedeninizi kısaca açıklayınız..."
    },
    app: {
      title: "AI Makyaj Danışmanı",
      subtitle: "Kişiselleştirilmiş profesyonel makyaj analizi için fotoğrafınızı yükleyin.",
      upload: "Fotoğraf Yükle",
      analyzing: "Analiz Ediliyor...",
      freeSummary: "Ücretsiz Yüz Profili",
      summaryTitle: "Yüz Profiliniz",
      faceShape: "Yüz Şekli",
      skinTone: "Cilt Tonu",
      premiumRequired: "Premium İçerik (Kilitli)",
      unlockPremium: "Havale ile Kilidi Aç",
      premiumPrice: "€5.00",
      suggestions: "Adım Adım Uygulama Rehberi",
      paletteTitle: "Size Özel Renk Paleti",
      stepsTitle: "Uygulama Adımları",
      productsTitle: "Önerilen Ürünler",
      dayNightTitle: "Gece & Gündüz Alternatifleri",
      proFixes: "Pro Düzeltmeler",
      time: "Süre",
      minutes: "Dk",
      day: "GÜNDÜZ",
      night: "GECE",
      technique: "Teknik",
      symmetry: "Simetri",
      eyeShape: "Göz Yapısı",
      option: "Seçenek",
      emptyProducts: "Bu görünüm için özel bir ürün gerekmiyor.",
      defaultFixes: "Yüz hatlarınız oldukça dengeli. Minimal dokunuşlarla doğal güzelliğinizi ön plana çıkarabilirsiniz.",
      errorProcessing: "Görüntü işleme hatası.",
      errorAnalysis: "Analiz hatası.",
      premiumAccess: "Premium Erişim",
      freePreview: "Ücretsiz Önizleme",
      changePhoto: "Fotoğrafı Değiştir",
      analyze: "Analiz Et",
      aiRequirement: "Gelişmiş Yapay Zeka Analizi için net ve iyi aydınlatılmış bir fotoğraf gereklidir.",
      virtualConsultant: "Sanal Güzellik Danışmanınız",
      aiDesc: "Yapay zeka destekli analiz aracımızla yüz şeklinizi, cilt tonunuzu ve size en çok yakışan renkleri keşfedin. Fotoğrafınızı yükleyin, profesyonel öneriler anında cebinize gelsin.",
      startFreeAnalysis: "Ücretsiz Analiz Başlat",
      personalReport: "Kişisel Rapor",
      matchSuccess: "%98 Eşleşme Başarısı"
    }
  },
  de: {
    nav: {
      home: "Startseite",
      services: "Dienstleistungen",
      products: "Produkte",
      booking: "Termine",
      blog: "Blog",
      about: "Über Uns",
      app: "AI Analyse",
      gallery: "Galerie",
      contact: "Kontakt",
      admin: "Admin"
    },
    hero: {
      title: "Entfalten Sie Ihre Wahre Schönheit",
      subtitle: "Professionelle Kunst trifft auf künstliche Intelligenz. Entdecken Sie mit Shenay Ileri das perfekte Make-up.",
      cta: "Termin buchen",
      aiBtn: "AI-Analyse testen",
      instagramBtn: "Auf Instagram folgen",
      instagram: "Folgen Sie auf Instagram"
    },
    contact: {
        title: "Kontakt & Buchung",
        phone: "Telefon",
        email: "E-Mail",
        address: "Adresse",
        whatsapp: "WhatsApp",
        followUs: "Folge uns"
    },
    payment: {
      title: "Zahlung per Banküberweisung",
      description: "Bitte überweisen Sie den Betrag, um die vollständige Premium-Analyse freizuschalten.",
      payButton: "Zur Überweisung",
      secure: "Sichere Banküberweisung",
      cardHolder: "KONTOLNHABER",
      expires: "GÜLTIG BIS",
      bankTransferTitle: "Bankverbindung",
      bankTransferDesc: "Bitte überweisen Sie den Gesamtbetrag auf das untenstehende Konto.",
      sentButton: "Ich habe die Zahlung gesendet"
    },
    admin: {
      title: "Shenay Admin Dashboard",
      adsTitle: "Werbekampagnen verwalten",
      uploadAd: "Neues Banner hochladen",
      loginTitle: "Admin Login",
      username: "Benutzername",
      password: "Password",
      loginBtn: "Anmelden",
      forgotPassword: "Passwort vergessen?",
      recoveryTitle: "Kontowiederherstellung",
      recoveryDesc: "Aus Sicherheitsgründen wenden Sie sich bitte an den Systementwickler.",
      lockedMessage: "Zu viele Fehlversuche. Anmeldung gesperrt.",
      loginError: "Ungültige E-Mail oder Passwort.",
      emailSupport: "E-Mail-Support",
      tryAgainIn: "Versuchen Sie es erneut in",
      emailLabel: "E-Mail",
      tabs: {
        overview: "Übersicht",
        appointments: "Termine",
        services: "Dienstleistungen",
        products: "Produkte",
        blog: "Blog",
        gallery: "Galerie",
        testimonials: "Bewertungen",
        team: "Team",
        banners: "Banner",
        invoices: "Rechnungen",
        orders: "Bestellungen",
        settings: "Einstellungen"
      },
      orderStatus: {
        pending: "Ausstehend",
        shipped: "Versandt",
        completed: "Abgeschlossen",
        cancelled: "Storniert",
        return_requested: "Rückgabe angefordert",
        returned: "Zurückgegeben",
        refunded: "Erstattet"
      },
      modalTitle: "Bearbeiten / Hinzufügen",
      cancel: "Abbrechen",
      saveAndPublish: "Speichern & Veröffentlichen",
      deleteConfirm: "Sind Sie sicher, dass Sie diesen Artikel löschen möchten?",
      saveSuccess: "Einstellungen erfolgreich gespeichert!",
      saveError: "Fehler beim Speichern der Einstellungen",
      deleteError: "Fehler beim Löschen des Artikels",
      invoiceTitle: "Rechnungsgenerator",
      invoiceNo: "Rechnungs-Nr",
      date: "Datum",
      customerName: "Kundenname",
      address: "Adresse",
      items: "Positionen",
      addPhoto: "Foto hinzufügen",
      addVideo: "Video hinzufügen",
      remove: "Entfernen",
      mediaGallery: "Mediengalerie",
      addItem: "+ Position hinzufügen",
      printDownload: "Drucken / PDF herunterladen",
      legalInfo: "Rechtliche Firmeninformationen",
      companyName: "Firmenname",
      companyAddress: "Firmenadresse",
      taxId: "Steuernummer",
      vatId: "USt-IdNr.",
      jurisdiction: "Gerichtsstand",
      bankInfo: "Bankverbindung",
      bankName: "Bankname",
      iban: "IBAN",
      bic: "BIC/SWIFT",
      accountHolder: "Kontoinhaber",
      saveLegalInfo: "Firmeninfos speichern",
      siteSettings: "Allgemeine Website-Einstellungen",
      siteTitle: "Seitentitel",
      heroSlogan: "Hero-Slogan",
      heroBackground: "Hero-Hintergrund",
      change: "Ändern",
      heroDesc: "Das große Hintergrundbild oben auf der Startseite. Empfohlene Größe: 1920x1080px (Horizontal)",
      contactInfo: "Kontaktinformationen",
      phone: "Telefon",
      email: "E-Mail",
      aboutMe: "Über mich",
      saveAll: "ALLE EINSTELLUNGEN SPEICHERN & VERÖFFENTLICHEN",
      logout: "Abmelden",
      newAdd: "Neu hinzufügen",
      management: "Verwaltung",
      noOrders: "Noch keine Bestellungen.",
      appointmentRequests: "Terminanfragen",
      customer: "Kunde",
      service: "Dienstleistung",
      status: "Status",
      action: "Aktion",
      confirmed: "Bestätigt",
      waiting: "Wartend",
      cancelled: "Storniert",
      amount: "Betrag",
      id: "ID",
      saving: "Speichern...",
      generalSiteSettings: "Allgemeine Website-Einstellungen",
      homeBackground: "Startseiten-Hintergrund",
      heroImage: "Hero-Bild",
      recommendedSize: "Empfohlene Größe",
      changePhoto: "Foto ändern",
      saveAllSettings: "ALLE EINSTELLUNGEN SPEICHERN",
      galleryManagement: "Galerie-Verwaltung",
      addNewPhoto: "Neues Foto hinzufügen",
      incomingOrders: "Eingehende Bestellungen",
      noOrdersYet: "Noch keine Bestellungen.",
      stock: "Lagerbestand",
      category: "Kategorie",
      rating: "Bewertung",
      comment: "Kommentar",
      role: "Rolle",
      bio: "Biografie",
      instagramLink: "Instagram Link",
      link: "Link",
      excerpt: "Auszug",
      price: "Preis",
      titleLabel: "Titel",
      invoiceHeader: "RECHNUNG",
      invoiceRecipient: "Empfänger",
      invoiceDesc: "Beschreibung",
      invoicePriceNet: "Preis (Netto)",
      invoiceVat: "MwSt",
      invoiceTotal: "Gesamt",
      invoiceSumNet: "Summe Netto",
      invoicePlusVat: "zzgl. MwSt 19%",
      invoiceTotalAmount: "Gesamtbetrag",
      invoiceBank: "Bankverbindung",
      invoiceThanks: "Vielen Dank für Ihren Auftrag!",
      invoiceDate: "Datum",
      invoiceNoLabel: "Rechnungs-Nr",
      pricePlaceholder: "z.B. €25.00",
      ratingPlaceholder: "(1-5)",
      currencySymbol: "€",
      vatSymbol: "%"
    },
    sections: {
      servicesTitle: "Dienstleistungen",
      productsTitle: "Produkte",
      blogTitle: "Blog & Tipps",
      bookTitle: "Termin buchen",
      aboutTitle: "Über Shenay Ileri",
      aboutText: "Shenay Ileri kombiniert jahrelange Erfahrung in der Schönheits- und Ästhetikbranche mit dem Ziel, das einzigartige Strahlen jeder Frau zum Vorschein zu bringen. Als Absolventin der Fames Face Akademie ist Shenay nicht nur Visagistin, sondern auch Schönheitscoach.",
      aboutRoles: [
          "Gründerin von Bridal Room & Academy",
          "Professionelles Make-up & Haarstyling",
          "Expertin für medizinische Hautpflege (Aquafacial)"
      ],
      bookBtn: "Bestätigen",
      buyBtn: "In den Warenkorb",
      readMore: "Mehr lesen",
      returnBtn: "Rücksendeantrag erstellen",
      bookFormName: "Name",
      bookFormNamePlaceholder: "Namen eingeben",
      bookFormPhone: "Telefon",
      bookFormPhonePlaceholder: "+49 ...",
      bookFormDate: "Datum",
      bookFormTime: "Uhrzeit",
      bookFormService: "Dienstleistung",
      bookFormSuccess: "Reservierungsanfrage erhalten!",
      bookServiceOptions: {
        bridal: "Braut Make-up",
        special: "Besonderes Event Make-up",
        skincare: "Hautpflege",
        brows: "Augenbrauendesign"
      },
      galleryTitle: "Portfolio & Galerie",
      gallerySubtitle: "Erleben Sie die natürlichsten und eindrucksvollsten Formen der Schönheit. Hier sind Auszüge aus unserer Arbeit.",
      contactTitle: "Kontaktieren Sie uns",
      testimonialsTitle: "Kundenbewertungen",
      teamTitle: "Unser Team",
      professionalArtist: "Professioneller Künstler",
      serviceDetailsTitle: "Service-Details",
      bookNow: "Termin buchen",
      bookDescription: "Reservieren Sie jetzt Ihren Platz für diesen Service. Entfalten Sie Ihre Schönheit mit professionellen Akzenten.",
      onlineBooking: "7/24 Online-Buchung",
      supportContact: "Kontaktieren Sie uns für Support",
      outOfStock: "NICHT VORRÄTIG",
      soldOut: "AUSVERKAUFT",
      notesLabel: "Notizen (Optional)",
      notesPlaceholder: "Alles, was Sie hinzufügen möchten...",
      goBack: "Zurück",
      share: "Teilen",
      whatsappTitle: "Schneller Kontakt per WhatsApp",
      whatsappDesc: "Sie können uns über WhatsApp schreiben, um einen Termin zu vereinbaren oder Informationen anzufordern.",
      followUs: "Folgen Sie uns",
      all: "Alle",
      other: "Andere",
      galleryAlt: "Galeriebild"
    },
    cart: {
      title: "Warenkorb",
      empty: "Ihr Warenkorb ist leer.",
      total: "Gesamt",
      checkout: "Bestellung bestätigen",
      shippingTitle: "Versanddetails",
      shippingDesc: "Bitte geben Sie Ihre Daten ein, um fortzufahren.",
      formName: "Vollständiger Name",
      formPhone: "Telefonnummer",
      formEmail: "E-Mail-Adresse",
      formAddress: "Adresse",
      formCity: "Stadt",
      formZip: "Postleitzahl",
      back: "Zurück",
      proceed: "Zur Zahlung",
      orderSuccessTitle: "Bestellung erhalten!",
      orderSuccessMsg: "Vielen Dank! Ihre Bestellung wurde erfolgreich in unserem System erfasst.",
      continueShop: "Weiter einkaufen"
    },
    returns: {
      title: "Rückgabe & Erstattung",
      policyTitle: "Widerrufsbelehrung",
      formTitle: "Rücksendeformular",
      orderId: "Bestellnummer",
      email: "E-Mail-Adresse",
      reason: "Grund für die Rücksendung",
      submitBtn: "Anfrage Senden",
      placeholderId: "z.B. 1001",
      placeholderEmail: "E-Mail der Bestellung",
      placeholderReason: "Bitte beschreiben Sie kurz den Grund..."
    },
    app: {
      title: "AI Make-up Berater",
      subtitle: "Laden Sie Ihr Foto hoch für eine personalisierte professionelle Make-up-Analyse.",
      upload: "Foto hochladen",
      analyzing: "Analysieren...",
      freeSummary: "Kostenloses Gesichtsprofil",
      summaryTitle: "Ihr Gesichtsprofil",
      faceShape: "Gesichtsform",
      skinTone: "Hautton",
      premiumRequired: "Premium-Inhalt (Gesperrt)",
      unlockPremium: "Freischalten (Überweisung)",
      premiumPrice: "€5.00",
      suggestions: "Schritt-für-Schritt-Anleitung",
      paletteTitle: "Ihre Farbpalette",
      stepsTitle: "Anwendungsschritte",
      productsTitle: "Empfohlene Produkte",
      dayNightTitle: "Tag & Nacht Look",
      proFixes: "Pro Korrekturen",
      time: "Dauer",
      minutes: "Min",
      day: "TAG",
      night: "NACHT",
      technique: "Technik",
      symmetry: "Symmetrie",
      eyeShape: "Augenform",
      option: "Option",
      emptyProducts: "Keine speziellen Produkte erforderlich.",
      defaultFixes: "Ihre Gesichtszüge sind sehr ausgeglichen. Mit minimalen Akzenten können Sie Ihre natürliche Schönheit unterstreichen.",
      errorProcessing: "Fehler bei der Bildverarbeitung.",
      errorAnalysis: "Analysefehler.",
      premiumAccess: "Premium-Zugang",
      freePreview: "Kostenlose Vorschau",
      changePhoto: "Foto ändern",
      analyze: "Analysieren",
      aiRequirement: "Die erweiterte KI-Analyse erfordert ein klares, gut beleuchtetes Foto.",
      virtualConsultant: "Ihr virtueller Schönheitsberater",
      aiDesc: "Entdecken Sie Ihre Gesichtsform, Ihren Hautton und die Farben, die am besten zu Ihnen passen, mit unserem KI-gestützten Analysetool. Laden Sie Ihr Foto hoch und erhalten Sie sofort professionelle Empfehlungen.",
      startFreeAnalysis: "Kostenlose Analyse starten",
      personalReport: "Persönlicher Bericht",
      matchSuccess: "98% Übereinstimmungsrate"
    }
  }
};

export const MOCK_ADS: AdBanner[] = [
  {
    id: 1,
    imageUrl: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=2069&auto=format&fit=crop",
    title: "Brautkollektion 2025",
    link: "#"
  },
  {
    id: 2,
    imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2070&auto=format&fit=crop",
    title: "Masterclass: Konturieren wie ein Profi",
    link: "#"
  }
];

export const GALLERY_ITEMS: GalleryItem[] = [
    { id: 1, image: "https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?q=80&w=2036&auto=format&fit=crop", caption: "Braut Make-up" },
    { id: 2, image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2070&auto=format&fit=crop", caption: "Soft Glam" },
    { id: 3, image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=2069&auto=format&fit=crop", caption: "Editorial" },
    { id: 4, image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=2070&auto=format&fit=crop", caption: "Hautpflege" },
    { id: 5, image: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=2070&auto=format&fit=crop", caption: "Workshop" }
];

export const SERVICES: Service[] = [
  {
    id: 1,
    title: "Braut Make-up & Haarstyling",
    description: "Der perfekte Look für Ihren besonderen Tag. Inklusive Probe und Gesichtsanalyse.",
    longDescription: "Wir stehen Ihnen mit unserem professionellen Braut-Make-up- und Haarstyling-Service zur Seite, damit Sie an Ihrem Hochzeitstag den einzigartigen Look erhalten, von dem Sie träumen. Gemeinsam mit Probeterminen ermitteln wir das Make-up, das am besten zu Ihren Gesichtszügen, dem Stil Ihres Brautkleides und Ihrem Hochzeitskonzept passt. Mit weltberühmten Kosmetikmarken bieten wir eine Arbeit an, die die ganze Nacht hält, auf Fotos makellos aussieht und vor allem Ihre natürliche Schönheit hervorhebt.",
    gallery: [
       { url: "https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?q=80&w=2036&auto=format&fit=crop", type: 'image' },
       { url: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2070&auto=format&fit=crop", type: 'image' },
       { url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=2069&auto=format&fit=crop", type: 'image' }
    ],
    image: "https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?q=80&w=2036&auto=format&fit=crop"
  },
  {
    id: 2,
    title: "Aquafacial Hautpflege",
    description: "Strahlende Haut durch Tiefenreinigung und Hydratisierung.",
    longDescription: "Aquafacial ist eine medizinische Hautpflegeanwendung, die die Haut tiefenwirksam reinigt, peelt, extrahiert und mit Feuchtigkeit versorgt. Dank spezieller Aufsätze befreit es Ihre Haut von abgestorbenen Zellen und pumpt gleichzeitig Vitamine, Mineralien und Hyaluronsäure in die unteren Hautschichten. Das Ergebnis: Sofort hellere, sauberere und lebendigere Haut.",
    gallery: [
       { url: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=2070&auto=format&fit=crop", type: 'image' },
       { url: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?q=80&w=2070&auto=format&fit=crop", type: 'image' }
    ],
    image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=2070&auto=format&fit=crop"
  },
  {
    id: 3,
    title: "Lash & Brow Lifting",
    description: "Professioneller Touch für vollere Brauen und geschwungene Wimpern.",
    longDescription: "Lernen Sie unsere Dienstleistungen Lash Lifting (Wimpernlifting) und Brow Lamination (Augenbrauenlaminierung) kennen, um Ihren Blick eindrucksvoller zu machen. Während Ihre Wimpern von der Wurzel bis zur Spitze geschwungen werden und so länger und voluminöser erscheinen, werden Ihre Augenbrauen nach oben gekämmt, fixiert und erhalten eine vollere Form. Der Effekt hält durchschnittlich 6-8 Wochen an.",
    gallery: [
       { url: "https://images.unsplash.com/photo-1588510002166-5121287130eb?q=80&w=1974&auto=format&fit=crop", type: 'image' },
       { url: "https://images.unsplash.com/photo-1596436570226-f78a87383637?q=80&w=2074&auto=format&fit=crop", type: 'image' }
    ],
    image: "https://images.unsplash.com/photo-1588510002166-5121287130eb?q=80&w=1974&auto=format&fit=crop"
  },
  {
    id: 4,
    title: "Make-up Workshop",
    description: "Lernen Sie, das Make-up aufzutragen, das am besten zu Ihrem Gesicht passt.",
    longDescription: "In unseren Make-up-Workshops, die einzeln oder in Gruppen organisiert werden, entdecken Sie Ihren eigenen Gesichtstyp, Ihren Hautunterton und die Farben, die am besten zu Ihnen passen. Wir lehren praktisch Themen wie die richtige Pinselverwendung, Foundation-Wahl, Eyeliner-Techniken und die Verwandlung von Tages- zu Abend-Make-up.",
    gallery: [
       { url: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=2070&auto=format&fit=crop", type: 'image' },
       { url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=2071&auto=format&fit=crop", type: 'image' }
    ],
    image: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=2070&auto=format&fit=crop"
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Shenay Signature Red",
    description: "Langanhaltender roter Lippenstift mit mattem Finish.",
    price: "€25.00",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=2030&auto=format&fit=crop",
    rating: 5,
    orderCount: 142,
    voteCount: 89
  },
  {
    id: 2,
    name: "Glow Serum",
    description: "Aufhellende Basis vor dem Make-up.",
    price: "€45.00",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1887&auto=format&fit=crop",
    rating: 4.8,
    orderCount: 230,
    voteCount: 156
  },
  {
    id: 3,
    name: "Kontur-Palette",
    description: "3-Farben-Konturpalette für jeden Hautton.",
    price: "€35.00",
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2070&auto=format&fit=crop",
    rating: 4.9,
    orderCount: 86,
    voteCount: 42
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Braut-Make-up-Trends 2025",
    excerpt: "Was Sie über das natürliche Strahlen und die Pastelltöne dieser Saison wissen müssen.",
    content: "In den Braut-Make-up-Trends 2025 treffen Natürlichkeit und Glanz aufeinander. Die intensiven Kontur-Anwendungen und matten Foundations der vergangenen Jahre weichen dem 'Glass Skin'-Look. In dieser Saison wird der bevorzugte Stil für Bräute leichtgewichtige Produkte und Creme-Rouges sein, die das eigene Strahlen der Haut hervorheben.\n\nBeim Augen-Make-up dominieren weiterhin Pfirsich-, Rosa- und Champagnertöne. Anstelle von übertriebenen künstlichen Wimpern werden Einzelwimpern für einen natürlicheren, aber eindrucksvolleren Blick angestrebt. Auf den Lippen kehren Nude-Lippenstifte mit 'Glossy'-Finish und leicht getönte Glosse zurück.\n\nBei den Haartrends weichen straffe Dutts unordentlichen, böhmischen Zöpfen und natürlichen Wellen. Perlen und frische Blumen stehen als Accessoires im Vordergrund.",
    date: "10. März 2025",
    image: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=2070&auto=format&fit=crop",
    gallery: [
        "https://images.unsplash.com/photo-1596436570226-f78a87383637?q=80&w=2074&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=2069&auto=format&fit=crop"
    ]
  },
  {
    id: 2,
    title: "Hautpflege im Winter",
    excerpt: "5 goldene Regeln zum Schutz Ihrer Haut bei kaltem Wetter.",
    content: "Die Wintermonate können dazu führen, dass die Haut durch Kälte und Wind austrocknet, rissig und empfindlich wird. In dieser Zeit ist es von entscheidender Bedeutung, Ihre Hautpflegeroutine an die Jahreszeit anzupassen.\n\n1. Vernachlässigen Sie die Feuchtigkeitspflege nicht: Wasserbasierte Feuchtigkeitscremes, die Sie im Sommer verwenden, können im Winter unzureichend sein. Wechseln Sie zu reichhaltigeren Cremes, die Ceramide und Hyaluronsäure enthalten.\n2. Verwenden Sie Sonnenschutz: Auch die Wintersonne schadet der Haut. Besonders bei verschneitem Wetter kann die Reflexion der UV-Strahlen die Haut verbrennen. Verwenden Sie weiterhin SPF 30+ Schutz.\n3. Vermeiden Sie heißes Wasser: Das Waschen des Gesichts mit sehr heißem Wasser zerstört die natürlichen Öle der Haut. Bevorzugen Sie lauwarmes Wasser.\n4. Lippenpflege: Verwenden Sie intensiv reparierende Balsame für trockene Lippen und machen Sie einmal pro Woche ein Peeling.\n5. Trinken Sie viel Wasser: Um den Feuchtigkeitshaushalt der Haut zu bewahren, muss sie auch von innen unterstützt werden. Achten Sie darauf, mindestens 2 Liter Wasser pro Tag zu trinken.",
    date: "15. Februar 2025",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=2070&auto=format&fit=crop",
    gallery: [
        "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=2070&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1552693673-1bf958298935?q=80&w=2073&auto=map&fit=crop"
    ]
  },
  {
    id: 3,
    title: "Die richtige Foundation-Wahl",
    excerpt: "Wie wählen Sie die richtige Foundation basierend auf Ihrem Hautunterton aus?",
    content: "Der wichtigste Schritt beim Make-up ist ein makelloses Teint-Make-up. Eine falsche Foundation-Wahl kann jedoch das gesamte Make-up ruinieren. Um die richtige Foundation auszuwählen, müssen Sie zunächst Ihren Hautunterton bestimmen.\n\n- Kühler (Cool) Unterton: Wenn Ihre Venen blau oder violett erscheinen, sind Foundations mit rosa Unterton für Sie geeignet.\n- Warmer (Warm) Unterton: Wenn Ihre Venen grün erscheinen, sollten Sie Foundations mit gelbem oder goldenem Unterton bevorzugen.\n- Neutraler (Neutral) Unterton: Wenn Ihre Venen sowohl grün als auch blau erscheinen, haben Sie Glück, Beigetöne werden Ihnen sehr gut stehen.\n\nAußerdem sollten Sie Foundation nicht am Handgelenk, sondern an der Stelle testen, an der Ihr Hals auf Ihre Kieferlinie trifft. Die richtige Farbe ist diejenige, die auf Ihrer Haut verschwindet.",
    date: "20. Januar 2025",
    image: "https://images.unsplash.com/photo-1631730486784-5456119f69ae?q=80&w=2075&auto=format&fit=crop",
    gallery: [
         "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2070&auto=format&fit=crop"
    ]
  }
];

export const RETURN_POLICIES = {
  tr: `**İade ve Geri Ödeme Politikası (Widerrufsrecht)**
Almanya Tüketici Yasaları ve Hijyen Yönetmeliğine (BGB) Uygundur.

**1. Cayma Hakkı (Widerrufsrecht)**
Siparişinizi teslim aldığınız tarihten itibaren **14 gün** içinde, herhangi bir gerekçe göstermeksizin sözleşmeden cayma hakkına sahipsiniz.

**2. Kozmetik Ürünlerinde Hijyen İstisnası (§ 312g Abs. 2 Nr. 3 BGB)**
Lütfen dikkat ediniz: Sağlık koruması ve hijyen nedenleriyle, **mühürlü/ambalajlı teslim edilen ve teslimattan sonra mührü/ambalajı açılmış kozmetik ürünler (ruj, krem, serum vb.) iade edilemez.**
Ürünün orijinal jelatini, koruma bandı veya kapağı açılmış ise, yasa gereği iade hakkı geçersiz olur.

**3. İade Süreci**
- İade etmek istediğiniz ürün, **açılmamış ve orijinal ambalajında** olmalıdır.
- Yandaki formu doldurarak veya müşteri hizmetlerimizle iletişime geçerek iade talebi oluşturunuz.
- Onaylanan iadeler için size bir iade adresi iletilecektir.
- Yasal düzenlemeler gereği, ürün kusurlu (defolu) olmadığı sürece **iade kargo ücreti müşteriye aittir.**

**4. Geri Ödeme**
İade edilen ürün depomuza ulaşıp "açılmamış" olduğu doğrulandıktan sonra, ödemeniz 14 gün içinde orijinal ödeme yönteminizle (Banka Havalesi vb.) iade edilecektir.`,

  de: `**Widerrufsbelehrung & Rückgaberichtlinien**
Gemäß BGB und Hygienevorschriften (§ 312g Abs. 2 Nr. 3 BGB).

**1. Widerrufsrecht**
Sie haben das Recht, binnen **14 Tagen** ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter die Waren in Besitz genommen haben.

**2. Ausschluss des Widerrufsrechts (Hygiene)**
Das Widerrufsrecht besteht nicht bei Verträgen zur Lieferung versiegelter Waren, die aus Gründen des Gesundheitsschutzes oder der Hygiene nicht zur Rückgabe geeignet sind, wenn ihre **Versiegelung nach der Lieferung entfernt wurde** (z.B. Lippenstifte, Cremes, Seren).

**3. Rücksendung**
- Die Ware muss **ungeöffnet und originalverpackt** sein.
- Bitte füllen Sie das nebenstehende Formular aus.
- Die unmittelbaren Kosten der Rücksendung der Waren tragen Sie, sofern die Ware nicht defekt geliefert wurde.

**4. Rückerstattung**
Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf bei uns eingegangen ist.`,

  en: `**Return & Refund Policy (Right of Withdrawal)**
Compliant with German Consumer Laws (BGB) and Hygiene Regulations.

**1. Right of Withdrawal**
You have the right to withdraw from this contract within **14 days** without giving any reason.

**2. Hygiene Exception (§ 312g Abs. 2 Nr. 3 BGB)**
Please note: For reasons of health protection and hygiene, **sealed cosmetic products (lipsticks, creams, etc.) cannot be returned if the seal or packaging has been opened after delivery.**
If the original seal/wrapping is broken, the right of return is void.

**3. Return Process**
- The item must be **unopened and in original packaging**.
- Fill out the form to request a return.
- The customer bears the direct cost of returning the goods unless the item was defective.

**4. Refund**
Once we receive and verify the returned item (unopened), we will refund the payment within 14 days using the original payment method.`
};